name: 'Repo Metadata Sync'
description: 'Github Action to sync repo metadata (description, url, and topics) from code to repo'
author: 'kitschpatrol'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
