publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - case-police
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  esbuild: true
  oxc-resolver: true
  puppeteer: true
  tree-sitter: true
  tree-sitter-python: true
  tree-sitter-ruby: true
  unrs-resolver: true
